.TH "DOCKER" "1" "Aug 2017" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-swarm\-update \- Update the swarm


.SH SYNOPSIS
.PP
\fBdocker swarm update [OPTIONS]\fP


.SH DESCRIPTION
.PP
Update the swarm


.SH OPTIONS
.PP
\fB\-\-cert\-expiry\fP=2160h0m0s
    Validity period for node certificates

.PP
\fB\-\-dispatcher\-heartbeat\fP=5s
    Dispatcher heartbeat period

.PP
\fB\-\-external\-ca\fP=
    Specifications of one or more certificate signing endpoints

.PP
\fB\-\-task\-history\-limit\fP=5
    Task history retention limit


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
    Print usage


.SH SEE ALSO
.PP
\fBdocker\-swarm(1)\fP
