.TH "DOCKER" "1" "Aug 2017" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-volume\-ls \- List volumes


.SH SYNOPSIS
.PP
\fBdocker volume ls [OPTIONS]\fP


.SH DESCRIPTION
.PP
Lists all the volumes Docker knows about. You can filter using the \fB\-f\fP or
\fB\-\-filter\fP flag. The filtering format is a \fBkey=value\fP pair. To specify
more than one filter,  pass multiple flags (for example,
\fB\-\-filter "foo=bar" \-\-filter "bif=baz"\fP)

.PP
There is a single supported filter \fBdangling=value\fP which takes a boolean of
\fBtrue\fP or \fBfalse\fP\&.


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filter\fP=[]
    Provide filter values (i.e. 'dangling=true')

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only display volume names


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
    Print usage


.SH SEE ALSO
.PP
\fBdocker\-volume(1)\fP
