.TH "DOCKER" "1" "Aug 2017" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-swarm \- Manage Docker Swarm


.SH SYNOPSIS
.PP
\fBdocker swarm\fP


.SH DESCRIPTION
.PP
Manage Docker Swarm


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
    Print usage


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-swarm\-init(1)\fP, \fBdocker\-swarm\-join(1)\fP, \fBdocker\-swarm\-join\-token(1)\fP, \fBdocker\-swarm\-leave(1)\fP, \fBdocker\-swarm\-update(1)\fP
