.TH "DOCKER" "1" "Aug 2017" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-service\-ps \- List the tasks of a service


.SH SYNOPSIS
.PP
\fBdocker service ps [OPTIONS] SERVICE\fP


.SH DESCRIPTION
.PP
List the tasks of a service


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filter\fP=
    Filter output based on conditions provided

.PP
\fB\-\-no\-resolve\fP[=false]
    Do not map IDs to Names


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
    Print usage


.SH SEE ALSO
.PP
\fBdocker\-service(1)\fP
