.TH "DOCKER" "1" "Aug 2017" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-node\-ps \- List tasks running on a node


.SH SYNOPSIS
.PP
\fBdocker node ps [OPTIONS] self|NODE\fP


.SH DESCRIPTION
.PP
List tasks running on a node


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filter\fP=
    Filter output based on conditions provided

.PP
\fB\-\-no\-resolve\fP[=false]
    Do not map IDs to Names


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
    Print usage


.SH SEE ALSO
.PP
\fBdocker\-node(1)\fP
