.TH "DOCKER" "1" "Aug 2017" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-swarm\-join\-token \- Manage join tokens


.SH SYNOPSIS
.PP
\fBdocker swarm join\-token [\-q] 
\[la]worker|manager\[ra]\fP


.SH DESCRIPTION
.PP
Manage join tokens


.SH OPTIONS
.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only display token

.PP
\fB\-\-rotate\fP[=false]
    Rotate join token


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
    Print usage


.SH SEE ALSO
.PP
\fBdocker\-swarm(1)\fP
