.TH "DOCKER" "1" "Aug 2017" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-node\-ls \- List nodes in the swarm


.SH SYNOPSIS
.PP
\fBdocker node ls [OPTIONS]\fP


.SH DESCRIPTION
.PP
List nodes in the swarm


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filter\fP=
    Filter output based on conditions provided

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only display IDs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
    Print usage


.SH SEE ALSO
.PP
\fBdocker\-node(1)\fP
